### ISSUE TITLE
Failed to generate javadoc 

### ISSUE THREAD

**Issue by Nexcius** [schibsted/account-sdk-android#124]
See https://github.com/Kotlin/dokka/issues/287 for details

Remember to publish JavaDoc artifacts for the UI and Smartlock modules when fixed:
- [ ] JavaDoc artifact for version 0.10.0 of the UI module published
- [ ] JavaDoc artifact for version 0.10.0 of the smartlock module published

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ui:dokkaJavadoc'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.ClassCastException: org.jetbrains.kotlin.descriptors.impl.LazyPackageViewDescriptorImpl cannot be cast to org.jetbrains.kotlin.descriptors.DeclarationDescriptorWithSource
        at org.jetbrains.dokka.DocumentationBuilderKt.sourcePsi(DocumentationBuilder.kt:890)
        at org.jetbrains.dokka.Kotlin.KotlinAsJavaDescriptorSignatureProvider.signature(KotlinAsJavaDescriptorSignatureProvider.kt:12)
        at org.jetbrains.dokka.DeclarationLinkResolver.tryResolveContentLink(DeclarationLinkResolver.kt:37)
        at org.jetbrains.dokka.DeclarationLinkResolver.resolveContentLink(DeclarationLinkResolver.kt:56)
        at org.jetbrains.dokka.Kotlin.DescriptorDocumentationParser.addTagToSeeAlso(DescriptorDocumentationParser.kt:139)
        at org.jetbrains.dokka.Kotlin.DescriptorDocumentationParser.parseDocumentationAndDetails(DescriptorDocumentationParser.kt:67)
        at org.jetbrains.dokka.Kotlin.DescriptorDocumentationParser.parseDocumentation(DescriptorDocumentationParser.kt:36)
        at org.jetbrains.dokka.KotlinAsJavaDocumentationParser.parseDocumentation(KotlinAsJavaDocumentationBuilder.kt:63)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.nodeForElement(JavaPsiDocumentationBuilder.kt:96)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.nodeForElement$default(JavaPsiDocumentationBuilder.kt:95)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.build(JavaPsiDocumentationBuilder.kt:170)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder$appendClasses$1.invoke(JavaPsiDocumentationBuilder.kt:69)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder$appendClasses$1.invoke(JavaPsiDocumentationBuilder.kt:43)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.appendChildren(JavaPsiDocumentationBuilder.kt:130)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.appendChildren$default(JavaPsiDocumentationBuilder.kt:126)
        at org.jetbrains.dokka.JavaPsiDocumentationBuilder.appendClasses(JavaPsiDocumentationBuilder.kt:69)
        at org.jetbrains.dokka.KotlinAsJavaDocumentationBuilder.buildPackageDocumentation(KotlinAsJavaDocumentationBuilder.kt:36)
        at org.jetbrains.dokka.DocumentationBuilder.appendFragments(DocumentationBuilder.kt:418)
        at org.jetbrains.dokka.DokkaGeneratorKt.buildDocumentationModule(DokkaGenerator.kt:161)
        at org.jetbrains.dokka.DokkaGenerator.appendSourceModule(DokkaGenerator.kt:77)
        at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:40)
        at org.jetbrains.dokka.DokkaBootstrapImpl.generate(DokkaBootstrapImpl.kt:77)
        at org.jetbrains.dokka.DelegatedInvocationHandler.invoke(ProxyUtils.kt:41)
        at com.sun.proxy.$Proxy144.generate(Unknown Source)
        at org.jetbrains.dokka.gradle.DokkaTask.generate(main.kt:319)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
```

**Comment by Astach** [comment]
Fixed by #196
