### ISSUE TITLE
Crash in EncryptionKeyProvider

### ISSUE THREAD

**Issue by mattec92** [schibsted/account-sdk-android#154]
### Summary
We (Aftonbladet) have some users who are crashing a lot in EncryptionKeyProvider.getKeyFromKeyStore. 

### Environment
- SDK Version: 0.9.0
- SDK Module: UI
- Android Version: See below 
- Device Info: See below

### Details
http://crashes.to/s/07b2f141eda

```
Caused by java.lang.NullPointerException
       at android.security.AndroidKeyStore.engineContainsAlias(AndroidKeyStore.java:415)
       at java.security.KeyStore.containsAlias(KeyStore.java:441)
       at com.schibsted.account.persistence.EncryptionKeyProvider.getKeyFromKeyStore(SourceFile:83)
       at com.schibsted.account.persistence.EncryptionKeyProvider.getStoredEncryptionKey(SourceFile:41)
       at com.schibsted.account.persistence.EncryptionKeyProvider.(SourceFile:34)
       at com.schibsted.account.persistence.SessionStorageDelegate.(SourceFile:23)
       at com.schibsted.account.persistence.UserPersistence.(SourceFile:26)
       at com.schibsted.account.session.User$Companion.resumeLastSession(SourceFile:192)
```

### Steps to reproduce
?

**Comment by Nexcius** [comment]
Hi Mattias

Thanks for the report! We'll be looking into this immediately.
