### ISSUE TITLE
Account Service observer crashes app when used in PendingIntent

### ISSUE THREAD

**Issue by schibsted-rafal-adamek** [schibsted/account-sdk-android#180]
### Summary
Account Service observer crashes app when used with `PendingIntent`.

We use push notifications in our app. They run `Activities` through `PendingIntent`. When we run an `Activity` with an `AccountService` hooked as `LifecycleObserver` and then leave the app, it crashes.

### Environment
- SDK Version: 0.10.0 (also 0.9.0)
- SDK Module: `ui`
- Android Version: 8.1
- Device Info: All emulators tested

### Details
Stack trace, screenshots or any other relevant information

Stacktrace:
```
Process: com.schibsted.publishing.hermes.aftenposten,
    java.lang.RuntimeException: Unable to stop activity {com.schibsted.publishing.hermes.aftenposten/com.schibsted.publishing.hermes.newsfeed.NewsfeedActivity}: java.lang.RuntimeException: Failed to call observer method
. . .
     Caused by: java.lang.IllegalArgumentException: Service not registered: com.schibsted.account.persistence.UserPersistenceService$Connection@81bd559
. . .
```

Full stacktrace:
```
com.schibsted.publishing.hermes.aftenposten E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.schibsted.publishing.hermes.aftenposten, PID: 18818
    java.lang.RuntimeException: Unable to stop activity {com.schibsted.publishing.hermes.aftenposten/com.schibsted.publishing.hermes.newsfeed.NewsfeedActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4345)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at android.arch.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:225)
        at android.arch.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193)
        at android.arch.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184)
        at android.arch.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at android.arch.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:308)
        at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:327)
        at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
        at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
        at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
        at android.arch.lifecycle.ReportFragment.onStop(ReportFragment.java:100)
        at android.app.Fragment.performStop(Fragment.java:2722)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1341)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
        at android.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:2997)
        at android.app.FragmentController.dispatchStop(FragmentController.java:222)
        at android.app.Activity.performStop(Activity.java:7188)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4340)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.IllegalArgumentException: Service not registered: com.schibsted.account.persistence.UserPersistenceService$Connection@81bd559
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1484)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1638)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:703)
        at com.schibsted.account.AccountService.unbind(AccountService.kt:39)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.arch.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:215)
        at android.arch.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193) 
        at android.arch.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184) 
        at android.arch.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
        at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354) 
        at android.arch.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:308) 
        at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:327) 
        at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137) 
        at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123) 
        at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121) 
        at android.arch.lifecycle.ReportFragment.onStop(ReportFragment.java:100) 
        at android.app.Fragment.performStop(Fragment.java:2722) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1341) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027) 
        at android.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:2997) 
        at android.app.FragmentController.dispatchStop(FragmentController.java:222) 
        at android.app.Activity.performStop(Activity.java:7188) 
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4340) 
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

### Steps to reproduce
Please let us know how to reproduce this issue

The simplest way is to invoke a notification with a pending intent pointing to an activity with the following lines: `lifecycle.addObserver(accountService)` in `onCreate` method of the `Activity`.

Here's the snippet to create a notification:

```
        anything.setOnClickListener {
            val NOTIFICATION_CHANNEL_ID = "push_notification"
            val notificationManager = applicationContext.getSystemService(Context.NOTIFICATION_SERVICE)
                    as NotificationManager

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                with(
                    NotificationChannel(
                        NOTIFICATION_CHANNEL_ID,
                        "some channel",
                        NotificationManager.IMPORTANCE_DEFAULT
                    )
                ) {
                    description = "some description"
                    notificationManager.createNotificationChannel(this)
                }
            }

            val notification = NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_ID)
                .setContentTitle("some title")
                .setContentText("some message")
                .setColor(ContextCompat.getColor(this, R.color.colorPrimary))
                .setAutoCancel(true)
                .setCategory(NotificationCompat.CATEGORY_EVENT)
                .setSmallIcon(R.drawable.ic_gallery)
                .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
                .setContentIntent(
                    TaskStackBuilder.create(this)
                    .addNextIntent(Intent(this, **ActivityWithAccountService**::class.java))
                    .getPendingIntent(0, PendingIntent.FLAG_UPDATE_CURRENT)!!)
                .build()
            NotificationManagerCompat.from(this).notify(13, notification)

            return@setOnMenuItemClickListener true
        }
```

#### How to reproduce:

1. Have an Activity with `AccountService` hooked
2. Create a notification with pending intent (snippet ^)
3. Builld and open the app.
4. Invoke notification (clickListener?)
5. (Without leaving the app) tap the newly created system notification.
6. Quit the app (tap back on the navigation bar).

#### What happens:

- app crashes

#### What should happen

- app should not crash

`UserPersistenceService` is added to the manifest, obviously. I will provide more info if required.

**Comment by Nexcius** [comment]
I was not able to reproduce this, but I've added a guard around the unbinding so that it does not crash the application. You should probably check that you're actually binding this correctly though by browsing the logs from the tag `SCHACC-ASRV`

**Comment by Astach** [comment]
As a workaround to let us time to find a proper fix, does it work with `bind` `unbind` and without `  lifecycle.addObserver(accountService)` ?

**Comment by schibsted-rafal-adamek** [comment]
@Astach, thanks for the response. The effect is the same.
