### ISSUE TITLE
Crash on identification screen

### ISSUE THREAD

**Issue by Astach** [schibsted/account-sdk-android#309]
### Summary
identificationPresenter has not been initialized.

### Environment
- SDK Version: all
- SDK Module: UI
- Android Version:  all
- Device Info:  all

### Details
```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property identificationPresenter has not been initialized 
at com.schibsted.account.ui.login.screen.identification.ui.AbstractIdentificationFragment.identifyUser(SourceFile:110) 
at com.schibsted.account.ui.login.screen.identification.ui.EmailIdentificationFragment$registerListeners$1.onClick(SourceFile:72) 
at android.view.View.performClick(View.java:6256) 
at android.view.View$PerformClick.run(View.java:24710) 
at android.os.Handler.handleCallback(Handler.java:789) 
at android.os.Handler.dispatchMessage(Handler.java:98) 
at android.os.Looper.loop(Looper.java:251) 
at android.app.ActivityThread.main(ActivityThread.java:6572) 
at java.lang.reflect.Method.invoke(Method.java) 
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
### Steps to reproduce
1. Go identification screen and enter info
2. Navigate to next screen
4. Rotate the screen
5. Go back
6. Press continue

**Comment by damianpetla** [comment]
We have that crash in Omni as well using SDK 1.0.0. It happens on various devices and Android versions.

**Comment by xserxses** [comment]
This issue poped out again 
```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property identificationPresenter has not been initialized
       at com.schibsted.account.ui.login.screen.identification.ui.AbstractIdentificationFragment.identifyUser(SourceFile:110)
       at com.schibsted.account.ui.login.screen.identification.ui.EmailIdentificationFragment$registerListeners$1.onClick(SourceFile:70)
       at android.view.View.performClick(View.java:5723)
       at android.view.View$PerformClick.run(View.java:22689)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6368)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```
in SDK '1.1.0'
