### ISSUE TITLE
ClassCastException in LoadClientInfoTask

### ISSUE THREAD

**Issue by sorbris** [schibsted/account-sdk-android#330]
### Summary
An exception is thrown when you try to go back and change email from the password prompt by using the "Change email"-option presented when clicking the "Not you?"-button.

### Environment
- SDK Version: 1.1.0
- SDK Module: account-sdk-android-ui
- Android Version: 8.0.0
- Device Info: Samsung S8

### Details
```08-23 13:14:22.321 13369 13369 D AndroidRuntime: Shutting down VM
08-23 13:14:22.323 13369 13369 E AndroidRuntime: FATAL EXCEPTION: main
08-23 13:14:22.323 13369 13369 E AndroidRuntime: Process: *, PID: 13369
08-23 13:14:22.323 13369 13369 E AndroidRuntime: java.lang.ClassCastException: com.schibsted.account.ui.ui.dialog.SelectorDialog cannot be cast to com.schibsted.account.ui.ui.dialog.LoadingDialogFragment
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.ui.login.LoadClientInfoTask.<init>(SourceFile:23)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.ui.login.BaseLoginActivity.startIdentificationFragment(SourceFile:239)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.ui.login.BaseLoginActivity.startIdentificationFragment$default(SourceFile:236)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.ui.login.flow.password.SignupContractImpl.onCredentialsRequested(SourceFile:32)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.engine.input.Credentials$Companion.request$core_release(SourceFile:43)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.engine.controller.SignUpController.getOrRequestCredentials(SourceFile:79)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.engine.controller.SignUpController.evaluate(SourceFile:47)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.engine.controller.SignUpController.evaluate(SourceFile:41)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.ui.navigation.Navigation.handleBackPressed(SourceFile:149)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.ui.login.flow.password.PasswordActivity.onBackPressed(SourceFile:74)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.ui.login.flow.password.PasswordActivity.onNavigateBackRequested(SourceFile:81)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.schibsted.account.ui.login.screen.password.PasswordFragment$onDialogRequested$1.onClick(SourceFile:133)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at android.view.View.performClick(View.java:6891)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:12651)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26083)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
08-23 13:14:22.323 13369 13369 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

### Steps to reproduce
1. Enter email
2. click continue
3. click not you?
4. click change e-mail

**Comment by Astach** [comment]
Fixed by #326
