### ISSUE TITLE
Retreiving stored user credentials fails 100% time on Huawei P20 device

### ISSUE THREAD

**Issue by Nilzor** [schibsted/account-sdk-android#388]
### Summary
Huawei P20 Pro: Logging in succeeds, but killing the app and restarting it causes the user to be logged out despite of having checked "remember me on this devices".

The error is not reproducable on Samsung S8

### Environment
- SDK Version: 1.6.0
- SDK Module: core/example
- Android Version: 8.1.0
- Device Info: Huawei P20 Pro

### Steps to reproduce
First time install of example app, current master branch. 
- Open example app
- Successfully log in on test environment and check "remember me on this device"
- Kill app
- Restart app.
- *expected*: Fetches credentials from local storage and relogin the user
- *actual* Fails with error message in logcat:

```

2019-06-03 13:20:56.604 5795-5795/com.schibsted.account.example E/SCHACC-PersistenceEncryption: Failed to decrypt content
    android.security.keystore.KeyNotYetValidException: Key not yet valid
        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:727)
        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:793)
        at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
        at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
        at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2668)
        at javax.crypto.Cipher.tryCombinations(Cipher.java:2575)
        at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2480)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:567)
        at javax.crypto.Cipher.init(Cipher.java:831)
        at javax.crypto.Cipher.init(Cipher.java:772)
        at com.schibsted.account.persistence.PersistenceEncryption.rsaDecrypt(PersistenceEncryption.kt:45)
        at com.schibsted.account.persistence.SessionStorageDelegate.getOriginalAesKey(SessionStorageDelegate.kt:177)
        at com.schibsted.account.persistence.SessionStorageDelegate.getOriginalAesKey(SessionStorageDelegate.kt:168)
        at com.schibsted.account.persistence.SessionStorageDelegate.readDataFromPersistence(SessionStorageDelegate.kt:83)
        at com.schibsted.account.persistence.SessionStorageDelegate.<init>(SessionStorageDelegate.kt:31)
        at com.schibsted.account.persistence.SessionStorageDelegate.<init>(SessionStorageDelegate.kt:28)
        at com.schibsted.account.persistence.UserPersistence.<init>(UserPersistence.kt:33)
        at com.schibsted.account.persistence.UserPersistenceReceiver.<init>(UserPersistenceReceiver.kt:20)
        at com.schibsted.account.persistence.UserPersistenceService.onCreate(UserPersistenceService.kt:45)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3805)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7377)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

**Comment by Nilzor** [comment]
5% of our users have this device. This needs to be prioritized

![image](https://user-images.githubusercontent.com/990654/60415656-088bc980-9bdc-11e9-8f13-a33ed90e81be.png)
