### ISSUE TITLE
Crash due to incorrect usage of okhttp3.Interceptor

### ISSUE THREAD

**Issue by sqrt1764** [schibsted/account-sdk-android#419]
### Summary
App crashed when doing the agreements request.

### Environment
- SDK Version: 1.9.0
- SDK Module: account-sdk-android-core
- Android Version: P
- Device Info: Samsung S8+

### Details

https://github.com/schibsted/account-sdk-android/blob/97e8ac644965de794d624d98119c72a14d2f8e34/core/src/main/java/com/schibsted/account/network/AuthInterceptor.kt#L134

Please execute line `failedResponse.close()` just before the linked line.

```
2019-10-24 09:57:30.981 27829-27955/no.ebok.android.debug E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: no.ebok.android.debug, PID: 27829
    java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:156)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.schibsted.account.network.AuthInterceptor.refreshToken$core_release(AuthInterceptor.kt:134)
        at com.schibsted.account.network.AuthInterceptor.intercept(AuthInterceptor.kt:111)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.schibsted.account.network.InternalInfoInterceptor.intercept(InfoInterceptor.kt:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

This error seems to occur in response to `User.agreements.getArgreementStatus(..)`. Async-status-fetching is started in the callback of `User.resumeLastSession(..)`.

**Comment by sqrt1764** [comment]
This now happens because of a call `User.resumeLastSession(..)`.

```
2019-11-04 11:08:24.080 5858-5858/no.ebok.android V/SCHACC-ClientConfiguration: Read config file:
    Environment:	https://identity-pre.schibsted.com/ 
    Client ID:	5ae..........435 
    Client Secret:	WCT..........Foy 
2019-11-04 11:08:24.132 5858-5858/no.ebok.android V/SCHACC-NetworkCallback: Fetching user agreements state
2019-11-04 11:08:24.139 5858-6486/no.ebok.android V/SCHACC-AuthInterceptor: Attempting to perform authenticated request (ReqId:0) to https://identity-pre.schibsted.com/api/2/user/25c214a5-bf45-59a3-bd17-4ae151640c8e/agreements
2019-11-04 11:08:24.140 5858-6486/no.ebok.android V/SCHACC-AuthInterceptor: Security checks passed for request (ReqId:0)

//

2019-11-04 11:08:24.549 5858-6486/no.ebok.android V/SCHACC-AuthInterceptor: Request (ReqId:0) returned 401, checking if token should be refreshed
2019-11-04 11:08:24.549 5858-6486/no.ebok.android V/SCHACC-AuthInterceptor: Found that token should be refreshed for request (ReqId:0)
2019-11-04 11:08:24.549 5858-6486/no.ebok.android V/SCHACC-AuthInterceptor: Refreshing token from request (ReqId:0)
2019-11-04 11:08:24.550 5858-6486/no.ebok.android V/SCHACC-VERBOSE: Refreshing user token

//


2019-11-04 11:08:24.763 5858-6486/no.ebok.android V/SCHACC-VERBOSE: Refreshing user token was successful

//

2019-11-04 11:08:24.763 5858-6486/no.ebok.android V/SCHACC-AuthInterceptor: Re-firing request (ReqId:0) after token refreshing

//

2019-11-04 11:08:24.765 5858-6486/no.ebok.android E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: no.ebok.android, PID: 5858
    java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:156)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.schibsted.account.network.AuthInterceptor.refreshToken$core_release(AuthInterceptor.kt:134)
        at com.schibsted.account.network.AuthInterceptor.intercept(AuthInterceptor.kt:111)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.schibsted.account.network.InternalInfoInterceptor.intercept(InfoInterceptor.kt:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)    
```

**Comment by sqrt1764** [comment]
# 💩

**Comment by sqrt1764** [comment]
# 💩
