### ISSUE TITLE
KeyStore warning output in logcat for Android 9

### ISSUE THREAD

**Issue by Nilzor** [schibsted/account-sdk-android#430]
Reproduced on Xiaomi Redmi with Android 9.0

Not sure of the consequences.

Solution tip: https://stackoverflow.com/questions/52024752/android-9-keystore-exception-android-os-servicespecificexception

````
2020-01-17 12:25:44.935 32666-584/no.aftenbladet.debug W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1967)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
        at java.security.KeyStore.getEntry(KeyStore.java:1560)
        at com.schibsted.account.persistence.EncryptionKeyProvider.getKeyFromKeyStore(EncryptionKeyProvider.kt:111)
        at com.schibsted.account.persistence.EncryptionKeyProvider.getStoredEncryptionKey$core_release(EncryptionKeyProvider.kt:49)
        at com.schibsted.account.persistence.EncryptionKeyProvider.<init>(EncryptionKeyProvider.kt:39)
        at com.schibsted.account.persistence.SessionStorageDelegate.<init>(SessionStorageDelegate.kt:28)
        at com.schibsted.account.persistence.UserPersistence.<init>(UserPersistence.kt:33)
        at com.schibsted.account.session.User$Companion.resumeLastSession(User.kt:195)
        at com.schibsted.publishing.hermes.authentication.HermesSpid$resumeLastSession$resumeUserSessionSingle$1.subscribe(HermesSpid.kt:125)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14349)
        at io.reactivex.Flowable.subscribe(Flowable.java:14295)
        at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.subscribeNext(FlowableRetryPredicate.java:123)
        at io.reactivex.internal.operators.flowable.FlowableRetryPredicate.subscribeActual(FlowableRetryPredicate.java:42)
        at io.reactivex.Flowable.subscribe(Flowable.java:14349)
        at io.reactivex.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:39)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver.onComplete(MaybeSwitchIfEmptySingle.java:95)
        at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:59)
        at io.reactivex.Maybe.subscribe(Maybe.java:4073)
        at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle.subscribeActual(MaybeSwitchIfEmptySingle.java:45)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14349)
        at io.reactivex.Flowable.subscribe(Flowable.java:14295)
        at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.subscribeNext(FlowableRetryPredicate.java:123)
        at io.reactivex.internal.operators.flowable.FlowableRetryPredicate.subscribeActual(FlowableRetryPredicate.java:42)
        at io.reactivex.Flowable.subscribe(Flowable.java:14349)
        at io.reactivex.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:39)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
2020-01-17 12:25:44.936 32666-584/no.aftenbladet.debug W/KeyStore:     at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:36)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.observers.DeferredScalarDisposable.complete(DeferredScalarDisposable.java:82)
        at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:73)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
        at com.schibsted.publishing.hermes.web.HermesCookieBakery$shouldRefreshCookies$1.subscribe(HermesCookieBakery.kt:49)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:36)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableOnErrorReturn.subscribeActual(ObservableOnErrorReturn.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:469)
        at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:324)
        at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:30)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:54)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservablePublish.connect(ObservablePublish.java:116)
        at io.reactivex.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:88)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
        at io.reactivex.Observable.subscribe(Observable.java:12051)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle.subscribeActual(ObservableElementAtSingle.java:37)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3310)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:570)
2020-01-17 12:25:44.937 32666-584/no.aftenbladet.debug W/KeyStore:     at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitNext(BehaviorSubject.java:565)
        at io.reactivex.subjects.BehaviorSubject.onNext(BehaviorSubject.java:268)
```

**Comment by birukoff** [comment]
Will be fixed in 1.12
