### ISSUE TITLE
lateinit property identificationPresenter has not been initialized

### ISSUE THREAD

**Issue by sorbris** [schibsted/account-sdk-android#463]
### Summary
The login flow can crash with an UninitializedPropertyAccessException if the user rotates the screen when in the password fragment and then reenters email.

It is not a very frequent crash among users but it is easy to recreate.

### Environment
- SDK Version: Multiple, tested on 1.12.1 & 1.13.0
- SDK Module: account-sdk-android-ui
- Android Version: Multiple, tested on Oreo and Pie
- Device Info: Emulator and Samsung S10

### Details
```
kotlin.UninitializedPropertyAccessException: lateinit property identificationPresenter has not been initialized
	at com.schibsted.account.ui.login.screen.identification.ui.AbstractIdentificationFragment.identifyUser(AbstractIdentificationFragment.kt:110)
	at com.schibsted.account.ui.login.screen.identification.ui.EmailIdentificationFragment$registerListeners$1.onClick(EmailIdentificationFragment.kt:86)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24701)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

### Steps to reproduce

1. Enter email
2. click next
3. Rotate screen
4. Go back to email input
5. Press next
6. App crashes

**Comment by zamzterz** [comment]
Thanks for the detailed report! 🙇 

Unfortunately I can't provide any ETA for a fix of this.
(Of course, a PR would be much appreciated and would speed it up significantly 🙂 )
